title: "Nick Leland Personal Site"
email: "nicholasrleland@gmail.com"
description: >-
  This is my personal website. I am using this space to host my resume, showcase projects, and occasionally write an article.
baseurl: ""
url: "https://nick-leland.github.io"
twitter_username: "jekyll-theme-cayman"
github_username: "kramdown"

# Build settings
remote_theme: "pages-themes/cayman@v0.2.0"
plugins:
  - jekyll-feed

# Navigation links
nav:
  - title: "Home"
    url: "/"
  - title: "Projects"
    url: "/projects"
  - title: "Blog"
    url: "/blog"
  - title: "Resume"
    url: "/resume"

